### ISSUE TITLE
Error when I tried to start recording

### ISSUE THREAD

**Issue by mjdileep** [amouniverso/ie-activex-voicerec#1]
![image](https://user-images.githubusercontent.com/6938724/57791120-bd1b7a00-7759-11e9-9f94-84a5276c2c22.png)

**Comment by amouniverso** [comment]
Did you install .ocx component? In cmd "regsvr32 IEActiveXVoicerec.ocx" 
Also check activex permission settings in IE browser.

**Comment by mjdileep** [comment]
Nope, I just opened the html file with IE11 along with all activeX permissions. Didn't install anything. Btw there is a .ocx in Release folder right?

**Comment by amouniverso** [comment]
@mjdileep Yes, or you can compile it for a target platform.
