### ISSUE TITLE
Errors when trying to register IEActiveXVoicerec.ocx

### ISSUE THREAD

**Issue by is343** [amouniverso/ie-activex-voicerec#2]
I'm running into errors when I try to register `IEActiveXVoicerec.ocx`.

I've tried administrator mode, System32 and WOW64 versions of `regsvr32`, full and relative paths for `IEActiveXVoicerec.ocx`, dragging and dropping, opening-with. I keep getting the same error.

It's telling me that it failed to load, and that the specified module could not be found.

The only time I don't get that error is when I run regsvr32 from the command line without specifying if it's the System32 or WOW64 folders' version of regsvr32. If I run the command this way it tells me that it might not be compatible with the my version of windows - hence why I tried to specify which version of `regsvr32` to use.

Any ideas on what I might be doing wrong with getting this registered?

I'm running a windows 10 64-bit machine.

**Comment by amouniverso** [comment]
You should try to recompile the .ocx for x64 arch from sources and specify win10 SDK in VisualStudio project options. It was only tested on win7 x32.

**Comment by is343** [comment]
Ah, ok thanks. I figured it must have been an issue like that. I started getting getting things set up to compile it for my environment, but I ran into compile errors centered on `sf_open_virtual` and one other thing being undefined. 
I'm not in the office at the moment. I'll try getting that sorted out tomorrow. 

If I can get everything compiled, registered, and working do you want me to make a PR with my x64 windows 10 ocx?

**Comment by amouniverso** [comment]
Yes, that would be great.

**Comment by is343** [comment]
So I was able to switch out for 64bit libs and change to a windows 10 sdk, but I'm still not able to get this registered. I'm not sure what the issue is. I don't know if the windows version is still off or what.

![Screen Shot 2019-08-30 at 18 10 53](https://user-images.githubusercontent.com/30599893/64009560-05b54280-cb53-11e9-811d-d49b9bb2fcf4.png)


Is there anything else that needs to be done? Nothing else needs to be copied, or installed? Just `regsvr32 IEActiveXVoicerec.ocx`?

You can check out [my fork here](https://github.com/is343/ie-activex-voicerec)

**Comment by amouniverso** [comment]
I've checked a x86 build on my windows 10 x64 machine and it seems to be working fine:

![2019-09-01_23-24-46](https://user-images.githubusercontent.com/9085137/64081983-d9472500-cd10-11e9-9544-c3b045968d1d.png)

Do you do exactly as in the screenshot?

**Comment by is343** [comment]
Aha! I was missing the dll files. They weren't in the release folder so I assumed that they weren't necessary. 
They were in the debug folder, but I didn't consider trying to install the debug if the release wasn't working.

I've got it registered, but now it seems like the `base64.html` demo crashes when the `Stop Recording` button is pressed. 

![image](https://user-images.githubusercontent.com/30599893/64086175-a719df80-cd71-11e9-9b44-b4acfe43f693.png)

**Comment by is343** [comment]
Restarting the system cleared the error. 

Thanks for the help in getting this working. 
I will try to smooth out the installation process by maybe bundling everything together for easy user install. I'll make a PR once I've got it together.
